#ifndef MODECONFIG_H
#define MODECONFIG_H

// Build profiles can override any switch with a -D build flag.
#ifndef GLOW_ENABLE_ALL_MODES
#define GLOW_ENABLE_ALL_MODES 0
#endif

#ifndef GLOW_ENABLE_STATIC_MODE
#define GLOW_ENABLE_STATIC_MODE 1
#endif

#ifndef GLOW_ENABLE_COLOR_PICKER_MODE
#define GLOW_ENABLE_COLOR_PICKER_MODE 1
#endif

#ifndef GLOW_ENABLE_RAINBOW_MODE
#define GLOW_ENABLE_RAINBOW_MODE 1
#endif

#ifndef GLOW_ENABLE_RANDOM_GLOW_MODE
#define GLOW_ENABLE_RANDOM_GLOW_MODE 1
#endif

#ifndef GLOW_ENABLE_BEACON_MODE
#define GLOW_ENABLE_BEACON_MODE 0
#endif

#ifndef GLOW_ENABLE_CANDLE_MODE
#define GLOW_ENABLE_CANDLE_MODE 0
#endif

#ifndef GLOW_ENABLE_SUNSET_MODE
#define GLOW_ENABLE_SUNSET_MODE 0
#endif

#ifndef GLOW_ENABLE_STROBE_MODE
#define GLOW_ENABLE_STROBE_MODE 0
#endif

#ifndef GLOW_ENABLE_MINI_GAME_MODE
#define GLOW_ENABLE_MINI_GAME_MODE 0
#endif

#if !GLOW_ENABLE_ALL_MODES && !GLOW_ENABLE_STATIC_MODE && \
    !GLOW_ENABLE_COLOR_PICKER_MODE && !GLOW_ENABLE_RAINBOW_MODE && \
    !GLOW_ENABLE_RANDOM_GLOW_MODE && !GLOW_ENABLE_BEACON_MODE && \
    !GLOW_ENABLE_CANDLE_MODE && !GLOW_ENABLE_SUNSET_MODE && \
    !GLOW_ENABLE_STROBE_MODE && !GLOW_ENABLE_MINI_GAME_MODE
#error "At least one GlowLight mode must be enabled"
#endif

#endif
